name: inventiv_critic_flutter
description: A flutter plugin for Critic integration.
version: 0.0.6
authors:
- Twin Sun, LLC <contact@twinsunsolutions.com>
- Caleb Hamilton <caleb@twinsunsolutions.com>
- Jami Couch <jami.couch@twinsunsolutions.com>
homepage: http://www.twinsunsolutions.com
repository: https://github.com/twinsunllc/critic_flutter

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  device_info: ^0.4.0+2
  package_info: ^0.4.0+5
  connectivity: ^0.4.3+5
  mime: ^0.9.6+2
  dio: ^2.0.18
  battery: ^0.2.3