name: inventiv_critic_flutter
description: A flutter plugin for Critic integration.
version: 0.4.0
homepage: https://www.twinsunsolutions.com
repository: https://github.com/twinsunllc/critic_flutter

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  device_info_plus: ^11.1.1
  package_info_plus: ^8.1.1
  connectivity_plus: ^6.1.0
  mime: ^2.0.0
  battery_plus: ^6.2.0