name: inventiv_critic_flutter
description: A flutter plugin for Critic integration.
version: 0.0.1
author: Twin Sun, LLC
homepage: twinsunsolutions.com

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  device_info: ^0.3.0
  package_info: ^0.3.2
